# Generated by Django 5.0.9 on 2024-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_keyword_searchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='last_record_final_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='searched_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last_search At'),
        ),
    ]
