services:
  docs:
    image: midnight_times_local_docs
    container_name: midnight_times_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./midnight_times:/app/midnight_times:z
    ports:
      - '9000:9000'
    command: /start-docs
